Repository AY2223S1-CS2103T-W16-3/tp, pull requests merged in 2022-11, with the labels that each got.

#190 Edit Developer Guide to remove mentions of address book and change hyperlinks
  docs/DeveloperGuide.md
Labels: priority.Medium, type.Task

#189 Increase test coverage across Appointment-related classes, remove Find command
  docs/diagrams/LogicClassDiagram.puml
  docs/team/kxrt.md
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/PastAppointment.java
  src/main/java/seedu/address/model/tag/MedicationMap.java
  src/test/java/seedu/address/logic/commands/CountCommandTest.java
  src/test/java/seedu/address/logic/commands/CreatePastAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CreatePastAppointmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/appointment/AppointmentTest.java
  src/test/java/seedu/address/model/appointment/PastAppointmentTest.java
  src/test/java/seedu/address/model/appointment/UpcomingAppointmentTest.java
  src/test/java/seedu/address/model/tag/MedicationMapTest.java
  src/test/java/seedu/address/model/tag/MedicationTest.java
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
  src/test/java/seedu/address/testutil/PastAppointmentBuilder.java
Labels: priority.Medium, type.Task

#191 Update developer guide
  docs/DeveloperGuide.md
  docs/diagrams/PastAppointmentSequenceDiagram.puml
  docs/images/PastAppointmentSequenceDiagram.png
Labels: priority.High, type.Task

#193 Bug Fixes and UG Update
  docs/UserGuide.md
  docs/images/ug-images/Person-Details-Panel-Clickability.png
  docs/images/ug-images/Person-List-Panel-Clickability.png
  docs/images/ug-images/Ui-explanations.png
  docs/images/ug-images/patientListPanel.gif
  docs/images/ug-images/patientViewPanel.gif
  src/main/java/seedu/address/logic/commands/CreatePastAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/DeletePastAppointmentCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/CreatePastAppointmentCommandTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: priority.Medium, type.Task, type.Bug, severity.Medium

#194 Fix incorrect text displayed and date parsing
  src/main/java/seedu/address/logic/commands/ConsultCommand.java
  src/main/java/seedu/address/logic/parser/CreatePastAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/getparsers/GetAppointmentByDateCommandParser.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/UpcomingAppointment.java
  src/main/java/seedu/address/model/person/HospitalWing.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPastAppointment.java
  src/test/java/seedu/address/model/appointment/AppointmentTest.java
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PastAppointmentBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High, type.Bug, severity.Low

#197 Include test case for Ward Number
  docs/team/nehcuy.md
  src/test/java/seedu/address/logic/commands/getcommands/GetHospitalWingCommandTest.java
  src/test/java/seedu/address/logic/commands/getcommands/GetInpatientCommandTest.java
  src/test/java/seedu/address/logic/commands/getcommands/GetMedicationCommandTest.java
  src/test/java/seedu/address/logic/commands/getcommands/GetOutpatientCommandTest.java
  src/test/java/seedu/address/logic/commands/getcommands/GetWardNumberCommandTest.java
  src/test/java/seedu/address/logic/parser/getparsers/GetHospitalWingCommandParserTest.java
  src/test/java/seedu/address/logic/parser/getparsers/GetWardNumberCommandParserTest.java
  src/test/java/seedu/address/model/person/HospitalWingTest.java
  src/test/java/seedu/address/model/person/WardNumberTest.java
Labels: priority.Medium, type.Task

#202 Implement more testcases
  src/main/java/seedu/address/logic/commands/DeletePastAppointmentCommand.java
  src/test/java/seedu/address/logic/commands/DeletePastAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/getcommands/GetFloorNumberCommandTest.java
  src/test/java/seedu/address/logic/commands/getcommands/GetPastAppointmentCommandTest.java
  src/test/java/seedu/address/logic/parser/DeletePastAppointmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/GetCommandParserTest.java
  src/test/java/seedu/address/logic/parser/getparsers/GetFloorNumberCommandParserTest.java
  src/test/java/seedu/address/logic/parser/getparsers/GetMedicationCommandParserTest.java
  src/test/java/seedu/address/logic/parser/getparsers/GetNameCommandParserTest.java
  src/test/java/seedu/address/logic/parser/getparsers/GetPastAppointmentCommandParserTest.java
  src/test/java/seedu/address/model/person/FloorNumberTest.java
  src/test/java/seedu/address/model/person/HospitalWingTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/tag/MedicationTest.java
Labels: priority.High

#203 Update developer guide
  docs/DeveloperGuide.md
  docs/diagrams/CountSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ModelPersonCompositionClassDiagram.puml
  docs/images/CountSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ModelPersonCompositionClassDiagram.png
  docs/team/kxrt.md
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: priority.High, type.Task, type.Bug, severity.Low

#201 Edit Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/GetHospitalWing.puml
  docs/diagrams/GetInpatientSequenceDiagram.puml
  docs/images/GetHospitalWingSequenceDiagram.png
  docs/images/GetInpatientSequenceDiagram.png
  docs/team/ryan-tan00.md
  src/main/java/seedu/address/model/person/Person.java
Labels: priority.Medium, type.Task

#199 Adds more test cases
  src/main/java/seedu/address/model/person/NextOfKin.java
  src/test/java/seedu/address/logic/commands/getcommands/GetAppointmentByDateCommandTest.java
  src/test/java/seedu/address/logic/commands/getcommands/GetHospitalWingCommandTest.java
  src/test/java/seedu/address/logic/parser/getparsers/GetAppointmentByDateCommandParserTest.java
  src/test/java/seedu/address/logic/parser/getparsers/GetHospitalWingCommandParserTest.java
  src/test/java/seedu/address/logic/parser/getparsers/GetNextOfKinCommandParserTest.java
  src/test/java/seedu/address/model/person/AppointmentByDatePredicateTest.java
  src/test/java/seedu/address/model/person/HospitalWingContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/HospitalWingTest.java
  src/test/java/seedu/address/model/person/NextOfKinPredicateTest.java
  src/test/java/seedu/address/model/person/NextOfKinTest.java
Labels: priority.High

#206 Edit my PPP
  docs/DeveloperGuide.md
  docs/team/charles1026.md
  docs/team/ryan-tan00.md
Labels: priority.Medium, type.Task

#210 Update diagrams, UG, DG and PPP
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AppointmentClassDiagram.puml
  docs/diagrams/AppointmentObjectDiagramBefore.puml
  docs/diagrams/AppointmentObjectDiagramWithBothAppt.puml
  docs/diagrams/AppointmentObjectDiagramWithPastAppt.puml
  docs/diagrams/PastAppointmentSequenceDiagram.puml
  docs/images/AppointmentClassDiagram.png
  docs/images/AppointmentObjectDiagramBefore.png
  docs/images/AppointmentObjectDiagramWithBothAppt.png
  docs/images/AppointmentObjectDiagramWithPastAppt.png
  docs/images/PastAppointmentSequenceDiagram.png
  docs/team/kxrt.md
Labels: priority.Low, type.Task

#211 Adds manual testing
  docs/DeveloperGuide.md
Labels: priority.High

#208 Edits test cases
  src/main/java/seedu/address/logic/commands/ConsultCommand.java
  src/main/java/seedu/address/model/person/NextOfKin.java
  src/test/java/seedu/address/logic/parser/getparsers/GetAppointmentByDateCommandParserTest.java
Labels: priority.High

#209 Edit DeveloperGuide.md
  docs/DeveloperGuide.md
  docs/diagrams/GetHospitalWing.puml
  docs/diagrams/GetInpatientSequenceDiagram.puml
  docs/images/GetHospitalWingSequenceDiagram.png
  docs/images/GetInpatientSequenceDiagram.png
  docs/images/LogicClassDiagram.png
Labels: priority.Medium, type.Task, type.Bug

#213 Update documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
Labels: priority.Low, type.Task

#214 Update PPP details
  docs/team/kxrt.md
Labels: priority.Low, type.Task

#215 Add Test Cases
  docs/team/charles1026.md
  src/main/java/seedu/address/logic/commands/ConsultCommand.java
  src/main/java/seedu/address/logic/parser/ConsultCommandParser.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/CommandHistory.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/ConsultCommandTest.java
  src/test/java/seedu/address/logic/parser/ConsultCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/ui/CommandHistoryTest.java
Labels: priority.Medium, type.Task

#216 Add clickability of person cards to DeveloperGuide.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/ryan-tan00.md
Labels: priority.Medium, type.Task

#219 Update PPP and Fix UG hyperlinks
  docs/AboutUs.md
  docs/UserGuide.md
  docs/team/charles1026.md
  src/test/java/seedu/address/logic/commands/ConsultCommandTest.java
Labels: priority.Medium, type.Task

#220 Fix Hyperlink for PPP
  docs/team/charles1026.md
Labels: priority.Low, type.Task

#221 Updates appton predicate
  src/main/java/seedu/address/model/person/AppointmentByDatePredicate.java
Labels: priority.Medium, type.Task

#222 Bug Fix: Clear invalid upcoming appointments when loading from storage
  docs/UserGuide.md
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/parser/ConsultCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: type.Bug, severity.High

#227 Update UG wording
  docs/UserGuide.md
Labels: priority.Low, type.Task

#229 Add reasons for usage for appt, delappt, consult
  docs/UserGuide.md
Labels: priority.Low, type.Task
