Repository AY2223S1-CS2103T-W16-3/tp, pull requests merged in 2022-10, with the labels that each got.

#36 Remove workflow as Netlify PR deployment was set up
  .github/workflows/pr-deployment.yaml
Labels: priority.low

#40 Update _config.yml
  docs/_config.yml
Labels: priority.low

#41 Update project documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/index.md
  docs/team/kxrt.md
Labels: priority.low

#45 Add hospital wing field to patient
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/HospitalWing.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.medium

#49 New Add & Edit Command and Person Fields
  .github/workflows/workflow.yml
  README.md
  docs/UserGuide.md
  docs/index.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/Prefix.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/FloorNumber.java
  src/main/java/seedu/address/model/person/HospitalWing.java
  src/main/java/seedu/address/model/person/NextOfKin.java
  src/main/java/seedu/address/model/person/PatientType.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/WardNumber.java
  src/main/java/seedu/address/model/tag/Medication.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedMedication.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NextOfKinTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/model/tag/MedicationTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#48 Get hw feature
  src/main/java/seedu/address/logic/commands/GetHospitalWingCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/GetHospitalWingCommandParser.java
  src/main/java/seedu/address/model/person/HospitalWingContainsKeywordsPredicate.java
Labels: priority.High

#51 Add count
  src/main/java/seedu/address/logic/commands/CountCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CountCommandTest.java
Labels: type.Story, priority.Medium

#52 Modify get /hw feature
  src/main/java/seedu/address/logic/commands/GetHospitalWingCommand.java
  src/main/java/seedu/address/model/Model.java
Labels: priority.High

#60 Update responsibilities in AboutUs
  docs/AboutUs.md
Labels: priority.Low, type.Task

#65 Implement appointment feature
  src/main/java/seedu/address/logic/commands/CreatePastAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/CreatePastAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/AppointmentType.java
  src/main/java/seedu/address/model/appointment/PastAppointment.java
  src/main/java/seedu/address/model/appointment/UpcomingAppointment.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPastAppointment.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story, priority.High

#64 Implement get /wn feature
  src/main/java/seedu/address/logic/commands/getcommands/GetHospitalWingCommand.java
  src/main/java/seedu/address/logic/commands/getcommands/GetWardNumberCommand.java
  src/main/java/seedu/address/logic/parser/GetCommandParser.java
  src/main/java/seedu/address/logic/parser/getparsers/GetFloorNumberCommandParser.java
  src/main/java/seedu/address/logic/parser/getparsers/GetHospitalWingCommandParser.java
  src/main/java/seedu/address/logic/parser/getparsers/GetWardNumberCommandParser.java
  src/main/java/seedu/address/model/person/FloorNumberContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/FloorNumberPredicate.java
  src/main/java/seedu/address/model/person/WardNumberPredicate.java
Labels: type.Story, priority.High

#67 Update appointment
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/CreatePastAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/CreatePastAppointmentCommandParser.java
  src/main/java/seedu/address/model/appointment/UpcomingAppointment.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPastAppointment.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Enhancement, type.Task, type.Bug, severity.High

#73 Implement get/nok feature
  src/main/java/seedu/address/logic/commands/getcommands/GetNextOfKinCommand.java
  src/main/java/seedu/address/logic/parser/GetCommandParser.java
  src/main/java/seedu/address/logic/parser/getparsers/GetNextOfKinCommandParser.java
  src/main/java/seedu/address/model/person/NextOfKinPredicate.java
Labels: priority.Medium

#75 Enable assertions, rename .jar filename
  build.gradle
Labels: priority.High, type.Task

#79 Update developer guide with Appointment feature
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AppointmentClassDiagram.puml
  docs/diagrams/AppointmentObjectDiagramBefore.puml
  docs/diagrams/AppointmentObjectDiagramWithBothAppt.puml
  docs/diagrams/AppointmentObjectDiagramWithPastAppt.puml
  docs/images/AppointmentClassDiagram.png
  docs/images/AppointmentObjectDiagramBefore.png
  docs/images/AppointmentObjectDiagramWithBothAppt.png
  docs/images/AppointmentObjectDiagramWithPastAppt.png
  docs/team/kxrt.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/parser/CreatePastAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/UpcomingAppointment.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
Labels: priority.High, type.Task, type.Bug, severity.High

#84 Update DeveloperGuide.md
  docs/DeveloperGuide.md
  docs/images/AddCommandParseArgsSequenceDiagram.png
  docs/images/AddCommandSequenceDiagram.png
  docs/images/PersonClassDiagram.png
Labels: priority.Low

#82 Add contact cards to main window
  src/main/java/seedu/address/logic/commands/GetCommand.java
  src/main/java/seedu/address/model/appointment/PastAppointment.java
  src/main/java/seedu/address/model/appointment/UpcomingAppointment.java
  src/main/java/seedu/address/model/person/NextOfKin.java
  src/main/java/seedu/address/ui/ContactCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/ContactListCard.fxml
Labels: priority.Medium

#86 Create DG draft
  docs/DeveloperGuide.md
  docs/diagrams/GetWardNumberSequenceDiagram.puml
  docs/diagrams/tracing/GetCommandSequenceDiagram.puml
  docs/images/tracing/GetCommandSequenceDiagram.png
Labels: priority.High, type.Task

#85 Update Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/GetAppointmentByDate.puml
  docs/diagrams/GetHospitalWing.puml
  docs/diagrams/GetNextOfKin.puml
  docs/images/GetAppointmentByDateSequenceDiagram.png
  docs/images/GetHospitalWingSequenceDiagram.png
  docs/images/GetNextOfKinSequenceDiagram.png
Labels: priority.High, type.Task

#80 Implement get /appt and add documentation for the get /inp and get /outp in the developer guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/GetInpatientSequenceDiagram.puml
  docs/images/GetInpatientSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/getcommands/GetPastAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/GetCommandParser.java
  src/main/java/seedu/address/logic/parser/getparsers/GetPastAppointmentCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
Labels: priority.Medium

#88 Edit user stories table formatting
  docs/DeveloperGuide.md
Labels: priority.Low, type.Bug, severity.VeryLow

#89 Update version number for v.1.3.trial
  src/main/java/seedu/address/MainApp.java
Labels: type.Task

#90 Update DG
  docs/DeveloperGuide.md
Labels: priority.Medium

#91 Count extension
  .github/workflows/workflow.yml
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/CountCommand.java
  src/main/java/seedu/address/logic/parser/GetCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/appointment/AppointmentType.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/tag/Medication.java
  src/main/java/seedu/address/ui/CountWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/CountWindow.css
  src/main/resources/view/CountWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CountCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: priority.Medium, type.Enhancement

#95 Add more testing
  src/main/java/seedu/address/model/person/FloorNumberPredicate.java
  src/main/java/seedu/address/model/person/HospitalWingContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/WardNumberPredicate.java
  src/test/java/seedu/address/logic/commands/getcommands/GetAppointmentByDateCommandTest.java
  src/test/java/seedu/address/logic/commands/getcommands/GetHospitalWingCommandTest.java
  src/test/java/seedu/address/logic/commands/getcommands/GetNameCommandTest.java
  src/test/java/seedu/address/logic/commands/getcommands/GetNextOfKinCommandTest.java
Labels: priority.High

#102 Rearrange GUI to give space for detailed person card
  src/main/java/seedu/address/logic/commands/getcommands/GetPastAppointmentCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: priority.Medium, type.Enhancement

#103 Shift command I/O in UI down, add unit tests for past appointments
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/appointment/PastAppointment.java
  src/main/java/seedu/address/model/appointment/UpcomingAppointment.java
  src/main/java/seedu/address/model/person/AppointmentByDatePredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CreatePastAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/getcommands/GetAppointmentByDateCommandTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Medium, type.Enhancement

#110 Update medication map, fix updating of census on patient deletion
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/tag/Medication.java
  src/main/java/seedu/address/model/tag/MedicationMap.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
Labels: priority.High, type.Bug, severity.High

#109 Adds new color schemes to GUI
  docs/team/peiyee88.md
  src/main/java/seedu/address/logic/parser/getparsers/GetHospitalWingCommandParser.java
  src/main/java/seedu/address/model/person/AppointmentByDatePredicate.java
  src/main/java/seedu/address/model/person/FloorNumberPredicate.java
  src/main/java/seedu/address/model/person/HospitalWing.java
  src/main/java/seedu/address/model/person/HospitalWingContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/WardNumberPredicate.java
  src/main/resources/view/CountWindow.css
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/HelpWindow.css
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/getparsers/GetAppointmentByDateCommandParserTest.java
  src/test/java/seedu/address/logic/parser/getparsers/GetHospitalWingCommandParserTest.java
  src/test/java/seedu/address/logic/parser/getparsers/GetNextOfKinCommandParserTest.java
  src/test/java/seedu/address/model/person/AppointmentByDatePredicateTest.java
  src/test/java/seedu/address/model/person/HospitalWingContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/HospitalWingTest.java
  src/test/java/seedu/address/model/person/NextOfKinPredicateTest.java
Labels: priority.High

#115 Fix bug in sample users, add support for no upcoming appointment
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/UpcomingAppointment.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
Labels: priority.High, type.Enhancement, type.Task, type.Bug, severity.High

#116 Add testcases to increase code coverage
  src/main/java/seedu/address/logic/commands/getcommands/GetPastAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/getcommands/GetWardNumberCommand.java
  src/main/java/seedu/address/logic/parser/getparsers/GetHospitalWingCommandParser.java
  src/main/java/seedu/address/model/person/FloorNumberPredicate.java
  src/main/java/seedu/address/model/person/HospitalWing.java
  src/main/java/seedu/address/model/person/HospitalWingContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/WardNumberPredicate.java
  src/test/java/seedu/address/logic/commands/GetCommandTest.java
  src/test/java/seedu/address/logic/commands/getcommands/GetAppointmentByDateCommandTest.java
  src/test/java/seedu/address/logic/commands/getcommands/GetFloorNumberCommandTest.java
  src/test/java/seedu/address/logic/commands/getcommands/GetHospitalWingCommandTest.java
  src/test/java/seedu/address/logic/commands/getcommands/GetWardNumberCommandTest.java
  src/test/java/seedu/address/logic/parser/GetCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/getparsers/GetHospitalWingCommandParserTest.java
Labels: priority.High

#118 Update user guide
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/findAlexDavidResult.png
  src/main/java/seedu/address/logic/commands/getcommands/GetHospitalWingCommand.java
  src/main/java/seedu/address/model/person/HospitalWing.java
Labels: priority.High

#126 Add PersonView Clickability Feature and Bug Fixes
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/WardNumber.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonViewPanel.java
  src/main/resources/view/PersonViewPanel.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High, type.Enhancement, severity.Medium

#129 Improve AddCommand Capabilities and Fix Appointment Bug
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/CreatePastAppointmentCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/PastAppointment.java
  src/main/java/seedu/address/model/appointment/UpcomingAppointment.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/resources/view/CountWindow.fxml
  src/main/resources/view/PersonViewPanel.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Enhancement, type.Bug, severity.Low

#130 Add deleteappt feature And Keyboard Shortcuts
  src/main/java/seedu/address/logic/commands/DeletePastAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeletePastAppointmentCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/CommandBox.java
Labels: priority.High, type.Enhancement

#128 Change color scheme
  src/main/java/seedu/address/logic/commands/GetCommand.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/CountWindow.css
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/MainWindow.fxml
Labels: priority.High

#133 Add Consult Command
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ConsultCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ConsultCommandParser.java
  src/main/java/seedu/address/logic/parser/DeletePastAppointmentCommandParser.java
  src/main/java/seedu/address/ui/CommandBox.java
Labels: priority.High, type.Enhancement

#134 Update user guide for v1.3.1
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/findAlexDavidResult.png
  src/main/java/seedu/address/model/person/Person.java
Labels: priority.High, type.Task, type.Bug, severity.High

#135 Add clickability info to UG
  docs/UserGuide.md
  docs/images/checkUp_512.png
  docs/images/checkUp_banner.png
  docs/team/kxrt.md
  docs/tutorials/AddRemark.md
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/address_book_32.png
  src/main/resources/images/checkUp_512.png
  src/main/resources/view/MainWindow.fxml
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/commons/util/AppUtilTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: priority.Medium, type.Bug, severity.Medium

#136 Update UI
  docs/images/Ui.png
  docs/images/findAlexDavidResult.png
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/ui/ContactCard.java
  src/main/java/seedu/address/ui/PersonViewPanel.java
  src/main/resources/images/ui/calendar.png
  src/main/resources/images/ui/help-line.png
  src/main/resources/images/ui/hospital-bed.png
  src/main/resources/images/ui/identification-card.png
  src/main/resources/images/ui/pills.png
  src/main/resources/view/ContactListCard.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonViewPanel.fxml
Labels: priority.High

#151 Adds glossary and checks formatting consistency
  docs/UserGuide.md
  docs/images/Ui.png
Labels: priority.High, type.Enhancement, type.Task, severity.Low

#171 Remove status bar
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StatusBarFooter.fxml
Labels: priority.Medium, type.Task

#178 Add parameter lists
  docs/UserGuide.md
  docs/team/kxrt.md
Labels: priority.Medium, type.Task

#182 UG Images Update And Clickability Update
  README.md
  docs/UserGuide.md
  docs/images/ug-images/Ui-explanations.png
  docs/images/ug-images/Ui.png
  docs/images/ug-images/addJohnDoeInpatientResult.png
  docs/images/ug-images/addJohnDoeOutpatientResult.png
  docs/images/ug-images/checkUp_banner.png
  docs/images/ug-images/editBetsyCrowerResult.png
  docs/images/ug-images/editJohnDoeResult.png
  docs/images/ug-images/getByNameAlexDavidResult.png
  docs/index.md
  docs/team/kxrt.md
  src/main/java/seedu/address/ui/PersonViewPanel.java
Labels: priority.Medium, severity.Low

#181 Fix get appointment by date feature bugs
  src/main/java/seedu/address/model/person/AppointmentByDatePredicate.java
Labels: priority.High

#183 User guide branch
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/WardNumber.java
Labels: type.Task, severity.Low

#184 Update user guide
  README.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/index.md
  docs/team/kxrt.md
Labels: priority.Medium, type.Task

#185 UG Update
  docs/UserGuide.md
  docs/images/ug-images/addCommand/addCommandResultBox.png
  docs/images/ug-images/addCommand/addJohnDoeInpatientResult.png
  docs/images/ug-images/addCommand/addJohnDoeOutpatientResult.png
  docs/images/ug-images/apptCommand/apptCommandResultBox.png
  docs/images/ug-images/apptCommand/apptJohnDoeCommandResult.png
  docs/images/ug-images/consultCommand/consultAlexYeohCommandResult.png
  docs/images/ug-images/consultCommand/consultCommandResultBox.png
  docs/images/ug-images/delapptCommand/delapptCommandResultBox.png
  docs/images/ug-images/delapptCommand/delapptJohnDoeCommandResult.png
  docs/images/ug-images/deleteCommand/deleteBetsyCrowerCommandResult.png
  docs/images/ug-images/deleteCommand/deleteCommandResultBox.png
  docs/images/ug-images/deleteCommand/deleteJohnDoeCommandResult.png
  docs/images/ug-images/editCommand/checkUp_banner.png
  docs/images/ug-images/editCommand/editBetsyCrowerResult.png
  docs/images/ug-images/editCommand/editCommandResultBox.png
  docs/images/ug-images/editCommand/editJohnDoeResult.png
  docs/images/ug-images/getCommand/getByNameAlexDavidResult.png
  docs/images/ug-images/getCommand/getCommandResultBox.png
  docs/images/ug-images/patientListPanel.gif
  docs/images/ug-images/patientViewPanel.gif
  docs/images/ug-images/viewCommand/viewCommandResultBox.png
  docs/team/kxrt.md
Labels: priority.High, type.Task

#187 Fix UG formatting issues
  docs/UserGuide.md
Labels: priority.High, type.Task, severity.Medium

#188 Update user guide
  docs/UserGuide.md
Labels: type.Bug, severity.Medium
